### ISSUE TITLE
Button "Check it" failed

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/SIGNALduino_TOOL#35]
@elektron-bbs,

bitte mal verifizieren.
Ich suche mir gerade den "Wolf" und bin der Meinung, wir hatten das als letzte Tat von uns zusammen nochmal geändert.

**Comment by HomeAutoUser** [comment]
Bitte nicht weiter suchen, Fehler gefunden und ich schiebe den fix gleich hoch.

**Comment by elektron-bbs** [comment]
Jetzt, wo ich gerade eine Vermutung hatte :-)
Liegt es an der Umstellung der Logausgaben?

**Comment by HomeAutoUser** [comment]
Ja genau daran lag es.
Zugleich habe ich gleich noch etwas Notizen vorgenommen damit es auch deutlich bleibt ;-)

**Comment by elektron-bbs** [comment]
Das passt zwar nicht hier dazu, aber ich habe auch gerade ein Problem:
Meine zwei noch auf Debian 8 basierenden Geräte machen kein Update von FHEM mehr. Ich bekomme immer folgende Fehlermeldung:

https://fhem.de/fhemupdate/controls_fhem.txt: Can't connect(2) to https://fhem.de:443:  SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Vieleicht hast du ja auf Anhieb eine Idee?

**Comment by HomeAutoUser** [comment]
Eine direkte Idee habe ich nicht soweit es das komplette FHEM ist.
Soben wurde nur das DEV-r34 gefixt weil da FHEM meldete falsche Größe der controls Datei.

Vielleicht wirst du mit dem Suchbefriff `SSL connect attempt failed error:14077410:SSL` fündig. Da gibt es einige Treffe und beim überfliegen scheint es ggf. PERL zu sein oder ein Debianpaket.

**Comment by sidey79** [comment]
Du musst eine neuere SSL bzw. TLS Version verwenden. z.B. v1.2 
Eventuell fehlen dir da auch Bibliotheken.
