### ISSUE TITLE
Falsche DMSG preamble

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/SIGNALduino_TOOL#5]
Wo kommt eigentlich der Wert für dmsg her? Der ist leider falsch wegen der Preamble.

https://github.com/RFD-FHEM/SIGNALduino_TOOL/blob/43dd600a630f3584148fbad775b647e12cf8884a/FHEM/lib/SD_Device_ProtocolList.json#L581-L590

**Comment by Ralf9** [comment]
Ja, stimmt der ist falsch es muss W94# heissen
https://github.com/RFD-FHEM/RFFHEM/pull/578

**Comment by elektron-bbs** [comment]
War ein typischer CTL+c/CTL+v-Error :-) Danke fürs Ändern.
